fjcoding/AT-BC-LAT-01

katas/chicken-sexing/kevin/chickenSexing.js, katas/chicken-sexing/kevin/chickenSexing.test.js
Running unit tests for chickenSexing.js
=> Adding code for chickenSexing.js and running tests

katas/chicken-sexing/daniel/chickenSexing.js, katas/chicken-sexing/daniel/chickenSexing.test.js
Hi Jose,
Please review this push, thanks!
=> The daniel test file is uncomment and the chicken-sexing.js function is developed

src/main/README.md, src/main/app.js, src/main/package-lock.json, src/main/package.json, src/main/routes/scenarios.js, src/main/server.js
First implementation of endpoints and routes for the API REST
=> Implementing endpoints and routes

package-lock.json, package.json, src/main/DB/db.js, src/main/routes/scenarios.js
-I ran the npm install for firebase admin and is already in the package.json
-The database connection done and waiting for testing if it's running.
=> Installed firebase admin dependency and in routes made the database config

package.json, src/main/app.js, src/main/routes/scenarios.js, src/main/server.js
Changed the required for the import as we agree and also change the way the "Dev" script works in order to "nodemon" accept this format.
=> Fixed changed the required for the import

README.md
This commit adds the instructions to run the server on the readme. Please comment if its something missing
=> Added instructions to run the server

src/test/modules/Actor.test.js, src/test/modules/Execution.test.js, src/test/modules/IndividualActions.test.js, src/test/modules/InteractiveActions.test.js, src/test/modules/Output.test.js, src/test/modules/Scenario.test.js
Moving the unit test to the correct folder
=> Modules units test moved on test/modules folder

src/main/modules/Main.js, src/main/modules/Scenario.js, src/test/modules/Main.test.js, src/test/modules/Scenario.test.js
Creation of a Main class which execute the path automatically to return the response directly.
=> Creation of Main class requested by API team

src/main/server.js
All the endpoints are working as the user story requires. We are talking with the modules team and they already made a class that will help us with the repeated code that it's a new step to refactor our code.
=> Endpoints working with the database

src/main/modules/Scenario.js, src/test/modules/Scenario.test.js
Change an "else if" for an "if" on Line 23 in Scenario.js
=> refactor on Scenario.js in order to get 100% branch coverege

src/main/api-utilities/ScenarioHandler.js, src/test/api-utilities/ScenarioHandler.test.js
Class in charge of push new actor and actions and in charge of replace weapon
=> Scenario handler implementation

src/main/api-utilities/PropertyVerifier.js, src/main/api-utilities/VerifierInterface.js, src/test/api-utilities/PropertyVerifier.test.js, src/test/api-utilities/VerifierInterface.test.js
This class is in charge of check if actors, actions and weapons are able to be added in an scenario. This interface is based in a facade pattern and will allow us to do those validation using one single line of code.
=> Verifier interface class

src/Diagram.drawio
Changes on the attributes and functions of the modules classes, the Diagram now looks like this
=> adding changes on class Diagram for modules classes

katas/design-patterns/Facade-pattern/example.js, katas/design-patterns/constructor-pattern/carexample.js, katas/design-patterns/constructor-pattern/fruitexample.js, katas/design-patterns/constructor-pattern/informationexample.js, katas/design-patterns/constructor-pattern/pizzaexample.js
This PR is for the examples of the constructor pattern
=> constructor pattern examples

src/main/modules/Execution.js
Removing health and pick weapon actions of Execution.js files
=> removing extra actions on Execution.js

src/main/db/queryHandler.js, src/main/routes/scenario.resource.js
-Change the return in QH get to give the json data and reduce the API
responsability. Checked the request with postman and is working.
=> PR to make QH get method return the json data

src/main/modules/Execution.js, src/main/modules/InteractiveActions.js, src/main/modules/Runner.js, src/main/modules/Scenario.js, src/test/modules/Execution.test.js, src/test/modules/Runner.test.js, src/test/modules/Scenario.test.js
Implementation for new requirements about the scenes handling.
=> Implementing new logic requirements for scenes handling

src/main/db/add.js, src/main/db/get.js, src/main/db/queryHandler.js, src/main/db/set.js
This PR is about the implementation of the design patterns in the database.
=> modification in the query handler to implement a facade design pattern

src/main/modules/Execution.js, src/main/modules/Validation.js, src/test/modules/Execution.test.js
Implementing SOLID principle of single responsabilities creating a new module which takes the control of the validation process during the execution.
=> Implementing encapsulation for Execution.js

src/main/db/mockQueryHandler.js, src/test/db/db.test.js, src/test/db/dbTestConstants.js
In here we commit the unit tests for database querys. 
Plz feel free to ask about the code
=> Unit test DB

src/main/modules/Execution.js, src/main/modules/Output.js, src/main/modules/Runner.js, src/main/modules/Scenario.js, src/main/modules/Validation.js, src/test/modules/Execution.test.js, src/test/modules/Output.test.js, src/test/modules/Runner.test.js, src/test/modules/Scenario.test.js
New changes are related to the required bullet movement and behavior depending of the weapon and the scope by scene, making the code extensable and keeping the correct functionality.
Some variables were renamed to make it easier to understand.
Unit test were improved by functionality and description.
Coverage for new functionalities around 100%.
=> Adding required functionality to bullets movement

src/main/modules/Execution.js, src/main/modules/Validation.js, src/test/modules/Runner.test.js
We noticed an unexpected behavior of action scenes that they were being decremented in the first Scenario scene which doesn't need to affect them, the issue was solved.
=> Improving implementation of action scenes

src/Diagram.drawio
=> adding Validation class to Class Diagram

src/main/api-utilities/PropertyVerifier.js, src/main/api-utilities/ScenarioAttributeVerifier.js, src/main/api-utilities/VerifierInterface.js, src/test/api-utilities/PropertyVerifier.test.js, src/test/api-utilities/ScenarioAttributeVerifier.test.js, src/test/api-utilities/VerifierInterface.test.js
In this PR the VerifierInterface was refactored to apply in a better way the facade patter using a new abstraction: ScenarioAttributeVerifier.
Verification like: actors.pos must be in the range (0, 100), weapon.power greather than 0 and scenario.scenes positive was implemented.
=> New verifications implementation

src/main/db/add.js, src/main/db/get.js, src/main/db/queryHandler.js, src/main/db/set.js
Just changed the names for add, get and set classes to match Jose
suggestion.
=> PR for class name changes
